clc



% p = gcp(); % get the current parallel pool
% f = parfeval(p,@serialConnection,1,3);
% value = fetchOutputs(f);
% 
% value

% t = datetime('now')
% formatOut = 'dd_mm_yyyy_HH_MM';
% 
% DateString = datestr(t,formatOut)

% function [] = timer_examp()
% 
% S.fh = figure('units','pixels',...
%               'position',[500 500 200 100],...
%               'menubar','none',...
%               'name','Timer_examp',...
%               'numbertitle','off',...
%               'resize','off');
% S.tx = uicontrol('style','text',...
%                  'unit','pix',...
%                  'position',[10 60 180 30],...
%                  'fontsize',14,...
%                  'string','3');  
% S.tmr = timer('Name','Countdown',...
%               'Period',1,...  % 10 minute snooze time.                
%               'StartDelay',.01,... 
%               'ExecutionMode','fixedSpacing',...
%               'StopFcn',@deleter);   % Function def. below.
% S.pb = uicontrol('style','push',...
%                  'units','pix',...
%                  'position',[10 10 180 40],...
%                  'fontsize',14,...
%                  'string','Start Countdown!',...
%                  'callback',{@pb_call,S});
% set(S.tmr,'TimerFcn',{@update_disp,S});             
% function [] = pb_call(varargin)
% % Callback for pushbutton, deletes one line from listbox.
% S = varargin{3};
% % Need to check string!
% set(S.tmr,'TasksToExecute',str2double(get(S.tx,'string')))  
% start(S.tmr);
% function [] = update_disp(varargin)
% S = varargin{3};
% N = str2double(get(S.tx,'string'));
% set(S.tx,'string',num2str(N-1));
% function deleter(obj,edata)   %#ok   M-Lint doesn't know the callback fmt.
% % Callback for stopfcn.
% wait(obj);
% delete(obj);
